backend:
  name: github
  repo: saulofilho/ffwd-site
  branch: master

media_folder: static/images
public_folder: '../../images'

collections:
  - name: 'pages'
    label: 'Pages'
    delete: false
    editor:
      preview: true
    files:
      - file: 'content/pages/contato.md'
        label: 'Contato Page'
        name: 'contato-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ContatoPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contato' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/blog.md'
        label: 'Blog Page'
        name: 'blog-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: BlogIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'blog' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/sobre.md'
        label: 'Sobre Page'
        name: 'sobre-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: SobrePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'sobre' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/home.md'
        label: 'Home Page'
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/projetos.md'
        label: 'Projetos Page'
        name: 'projetos-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ProjetosIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'projetos' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/pessoas.md'
        label: 'Pessoas Page'
        name: 'pessoas-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: PessoasPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'pessoas' }
          - { label: Title, name: title, widget: string }

  - name: posts
    label: Blog Posts
    editor:
      preview: true
    folder: content/posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: SinglePost }
      - { label: Date, name: date, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { label: Slug Title, name: title, widget: string, required: false }
      - { label: Post Title, name: PostTitle, widget: string, required: false }
      - { label: Post Text, name: PostText, widget: text, required: false }
      - { label: Post About Desktop, name: PostAboutDesktop, widget: text, required: false }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - label: 'Categories'
        name: 'categories'
        widget: 'list'
        required: false
        fields:
          - label: 'Category'
            name: 'category'
            widget: 'relation'
            collection: 'postCategories'
            searchFields: ['title']
            valueField: 'title'
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'

  - name: cases
    label: Cases Posts
    editor:
      preview: true
    folder: content/cases
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: CasePost }
      - { label: Date, name: date, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { label: Case Number and Client Title, name: ClientTitle, widget: string, required: false }
      - { label: Home Title, name: title, widget: string, required: false }
      - { label: Home Description, name: HomeDescription, widget: text, required: false }
      - {
        label: Home Image,
        name: HomeImage,
        widget: image,
        required: false,
      }
      - {
        label: Home Image Mob,
        name: HomeImageMob,
        widget: image,
        required: false,
      }
      - { label: Projetos Page Title, name: ProjetosTitle, widget: string, required: false }
      - { label: Projetos Page Description, name: ProjetosDescription, widget: text, required: false }
      - { label: Case Title, name: CaseTitle, widget: string, required: false }
      - { label: Case About, name: CaseAbout, widget: markdown, required: false }
      - label: 'Case Container'
        name: 'container'
        widget: 'list'
        required: false
        types:
        - label: 'Add Image'
          name: 'AddImage'
          widget: image
          fields:
            - { name: image, label: image, widget: image, required: false }
            - { name: alt, label: Alt, widget: string, required: false }
        - label: 'Add Image Mob'
          name: 'AddImageMob'
          widget: image
          fields:
            - { name: imagemob, label: image, widget: image, required: false }
            - { name: altmob, label: Alt, widget: string, required: false }
        - label: 'Add Text'
          name: 'AddText'
          widget: markdown
          fields:
            - { name: text, label: text, widget: markdown, required: false }
        - label: 'Add YouTube'
          name: 'AddText'
          widget: markdown
          fields:
            - { name: youtube, label: youtube, widget: markdown, required: false }
      - { label: Extra Content, name: body, widget: markdown, required: false }
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'
        required: false

  - name: vaga
    label: Vagas Posts
    editor:
      preview: true
    folder: content/vaga
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: VagaPost }
      - { label: Date / Order, name: date, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { label: Header Title, name: header, widget: string, required: false }
      - { label: Vaga Title, name: title, widget: string, required: false }
      - { label: Vaga About, name: about, widget: text, required: false }
      - { label: Vaga Overview, name: overview, widget: markdown, required: false }
      - { label: Vaga Like To See, name: LikeToSee, widget: markdown, required: false }
      - { label: Link, name: link, widget: string, required: false }
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'

  - name: postCategories
    label: Post Category
    editor:
      preview: false
    folder: content/postCategories
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: BlogIndex }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }

  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
