backend:
  name: git-gateway
  branch: master

display_url: https://santacontabilidade-blog.netlify.app/
media_folder: static/images
public_folder: '../../images'

collections:
  - name: 'pages'
    label: 'Pages'
    delete: false
    editor:
      preview: true
    files:
      - file: 'content/pages/contato.md'
        label: 'Contato Page'
        name: 'contato-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ContatoPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contato' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/blog.md'
        label: 'Blog Page'
        name: 'blog-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: BlogIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'blog' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/sobre.md'
        label: 'Sobre Page'
        name: 'sobre-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: SobrePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'sobre' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/home.md'
        label: 'Home Page'
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/projetos.md'
        label: 'Projetos Page'
        name: 'projetos-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ProjetosIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'projetos' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/pessoas.md'
        label: 'Pessoas Page'
        name: 'pessoas-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: PessoasPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'pessoas' }
          - { label: Title, name: title, widget: string }

  - name: posts
    label: Blog Posts
    editor:
      preview: true
    folder: content/posts
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: SinglePost }
      - { label: Date, name: date, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { label: Slug Title, name: title, widget: string, required: false }
      - { label: Post Title, name: PostTitle, widget: string, required: false }
      - { label: Post Text, name: PostText, widget: markdown, required: false }
      - { label: Post About Desktop, name: PostAboutDesktop, widget: markdown, required: false }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'

  - name: cases
    label: Cases Posts
    editor:
      preview: true
    folder: content/cases
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: CasePost }
      - { label: Date, name: date, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { label: Case Number and Client Title, name: ClientTitle, widget: string, required: false, hint: 'home page' }
      - { label: Home Title, name: title, widget: string, required: false, hint: 'home page' }
      - { label: Home Description, name: HomeDescription, widget: text, required: false, hint: 'home page' }
      - {
        label: Home Image,
        name: HomeImage,
        widget: image,
        required: false,
      }
      - {
        label: Home Image Mob,
        name: HomeImageMob,
        widget: image,
        required: false,
      }
      - { label: Projetos Page Title, name: ProjetosTitle, widget: string, required: false, hint: 'projetos page' }
      - { label: Projetos Page Description, name: ProjetosDescription, widget: text, required: false, hint: 'projetos page' }
      - { label: Case Title, name: CaseTitle, widget: string, required: false, hint: 'case page' }
      - { label: Case About, name: CaseAbout, widget: markdown, required: false, hint: 'case page' }
      - { label: Image 1, name: image1, widget: image, required: false }
      - { label: Image 1 mob, name: image1mob, widget: image, required: false }
      - { label: Title 1, name: title1, widget: string, required: false, hint: 'ex.: desafio' }
      - { label: Text 1, name: text1, widget: markdown, required: false, hint: 'ex.: texto desafio' }
      - label: 'Imgs and YT Container'
        name: 'container1'
        widget: 'list'
        required: false
        types:
        - label: 'Image'
          name: 'AddImage'
          fields:
            - { name: image, label: image, widget: image, required: false }
            - { name: imagemob, label: image mob, widget: image, required: false }
            - { name: alt, label: Alt, widget: string, required: false }
        - label: 'YouTube'
          name: 'AddYouTube'
          fields:
            - { name: youtube, label: youtube, widget: markdown, required: false }
      - { label: Title 2, name: title2, widget: string, required: false, hint: 'ex.: solucao' }
      - { label: Text 2, name: text2, widget: markdown, required: false, hint: 'ex.: texto solucao' }
      - { label: Title 3, name: title3, widget: string, required: false, hint: 'ex.: o filme' }
      - label: 'Imgs and YT Container'
        name: 'container2'
        widget: 'list'
        required: false
        types:
        - label: 'Image'
          name: 'AddImage'
          fields:
            - { name: image, label: image, widget: image, required: false }
            - { name: imagemob, label: image mob, widget: image, required: false }
            - { name: alt, label: Alt, widget: string, required: false }
        - label: 'YouTube'
          name: 'AddYouTube'
          fields:
            - { name: youtube, label: youtube, widget: markdown, required: false }
      - { label: Title 4, name: title4, widget: string, required: false, hint: 'ex.: resultados' }
      - label: 'Resultados Container'
        name: 'resultados'
        widget: 'list'
        required: false
        types:
        - label: 'texts'
          name: 'texts'
          fields:
            - { name: title, label: title, widget: string, required: false, hint: 'ex.: +1 mi' }
            - { name: text, label: text, widget: text, required: false, hint: 'ex.: MIDÍA ESPONTÂNEA*' }
            - { name: sub1, label: sub 1, widget: text, required: false, hint: 'ex.: do zero a' }
            - { name: sub2, label: sub 2, widget: text, required: false, hint: 'ex.: *Whatsapp não contabilizado' }
            - { name: text2, label: text 2, widget: markdown, required: false, hint: 'ex.: long copy' }
      - { label: resultados image, name: resultadosimage, widget: image, required: false }
      - { label: resultados image mob, name: resultadosimagemob, widget: image, required: false }
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'
        required: false

  - name: vaga
    label: Vagas Posts
    editor:
      preview: true
    folder: content/vaga
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: VagaPost }
      - { label: Date, name: date, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { label: Header Title, name: header, widget: string, required: false }
      - { label: Vaga Title, name: title, widget: string, required: false }
      - { label: Vaga About, name: about, widget: text, required: false }
      - { label: Vaga Overview, name: overview, widget: markdown, required: false }
      - { label: Vaga Like To See, name: LikeToSee, widget: markdown, required: false }
      - { label: Link, name: link, widget: string, required: false }
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'

  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
